-- AddForeignKey
ALTER TABLE `Fixture` ADD FOREIGN KEY (`HomeTeamId`) REFERENCES `Teams`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Fixture` ADD FOREIGN KEY (`AwayTeamId`) REFERENCES `Teams`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
